### ISSUE TITLE
Config settings related to Image Upload URL not being used

### ISSUE THREAD

**Issue by msevestre** [galetahub/ckeditor#322]
Hi there,

I am using ckeditor and would like to implement an upload functionality inside a mountable engine.
Everything works great if CKEditor is mounted inside the main rails app by extending the routes like so

``` ruby
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
end
```

What I would like however, is not to pollute the route of the main app and simply mount CKEditor inside my engine like so

``` ruby
MyEngine::Engine.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
end
```

When using the upload functionality I get an error that the route `/ckeditor/pictures` does not exist. That makes sense since I haven't touched any of the configuration

I created a config.js file in which i set

``` js
CKEDITOR.config.filebrowserBrowseUrl = "/myengine/ckeditor/attachment_files";
CKEDITOR.config.filebrowserFlashBrowseUrl ="/myengine/ckeditor/attachment_files";
CKEDITOR.config.filebrowserFlashUploadUrl = "/myengine/ckeditor/attachment_files";
CKEDITOR.config.filebrowserImageBrowseLinkUrl = "/myengine/ckeditor/pictures";
CKEDITOR.config.filebrowserImageBrowseUrl = "/myengine/ckeditor/pictures";
CKEDITOR.config.filebrowserImageUploadUrl = "/myengine/ckeditor/pictures";
 CKEDITOR.config.filebrowserUploadUrl = "/myengine/ckeditor/attachment_files";
```

Unfortunately, this url are not being used when browsing for files and I am still getting that `ckeditor/pictures` not found .

My options are being set property (debugged in Chrome DevTools). 

The route `/myengine/ckeditor/picutres` is also accessible. 

I am unsure what to do next and would appreciate any pointer on what I am doing wrong.

Thanks
Michael

**Comment by opan** [comment]
hi sir, i'm also use ckedior inside an rails engine, but i've always get this error message
```erb
/home/ncr-01/projects/nstcms/nst_cms_engine/config/initializers/ckeditor.rb:2:in `<top (required)>': undefined method `setup' for Ckeditor:Module (NoMethodError)
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `load'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `block in load'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `load'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/engine.rb:648:in `block in load_config_initializer'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.4/lib/active_support/notifications.rb:161:in `instrument'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/engine.rb:647:in `load_config_initializer'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/engine.rb:611:in `each'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/initializable.rb:30:in `run'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/ncr-01/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
	from /home/ncr-01/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
	from /home/ncr-01/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
	from /home/ncr-01/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
	from /home/ncr-01/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/tsort.rb:209:in `block in each_strongly_connected_component_from'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/initializable.rb:44:in `each'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /home/ncr-01/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/tsort.rb:203:in `each_strongly_connected_component_from'
	from /home/ncr-01/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
	from /home/ncr-01/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/tsort.rb:180:in `each'
	from /home/ncr-01/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
	from /home/ncr-01/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/application.rb:300:in `initialize!'
	from /home/ncr-01/projects/nstcms/test_cms/config/environment.rb:5:in `<top (required)>'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/application.rb:276:in `require'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/application.rb:276:in `require_environment!'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:147:in `require_application_and_environment!'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/ncr-01/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

```
which tell ```setup``` method is undefined in ```Ckeditor``` object on my ```ckeditor.rb``` file. am i miss something? i think i just have to run ``` rails g ckeditor:install ``` command and everything should be fine.

thanks.

**Comment by krukgit** [comment]
To change the upload path copy the default `config.js` file and change the urls listed at the top:
```
CKEDITOR.editorConfig = function( config )
{
  config.filebrowserBrowseUrl = "/admin/ckeditor/attachment_files";
  config.filebrowserFlashBrowseUrl = "/admin/ckeditor/attachment_files";
  config.filebrowserFlashUploadUrl = "/admin/ckeditor/attachment_files";
  config.filebrowserImageBrowseLinkUrl = "/admin/ckeditor/pictures";
  config.filebrowserImageBrowseUrl = "/admin/ckeditor/pictures";
  config.filebrowserImageUploadUrl = "/admin/ckeditor/pictures";
  config.filebrowserUploadUrl = "/admin/ckeditor/attachment_files";

  ...
```

**Comment by ljonny18** [comment]
Did you resolve this - I am currently facing the same problem. 
Thanks,
Jon.
