### ISSUE TITLE
Heroku precompile bug

### ISSUE THREAD

**Issue by joshualcoffee** [galetahub/ckeditor#388]
Assets are precompiling fine locally, however when I push to heroku it throws this error:

```
Asset logical path has no extension: bundle/ruby/2.0.0/gems/ckeditor-4.0.9/Gemfile
       (in /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/ckeditor-4.0.9/app/assets/javascripts/ckeditor/override.js.erb)
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/asset.rb:36:in `initialize'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:380:in `new'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:380:in `build_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/index.rb:94:in `block in build_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/caching.rb:58:in `cache_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/index.rb:93:in `build_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:287:in `find_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/index.rb:61:in `find_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:295:in `[]'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-rails-2.0.1/lib/sprockets/rails/helper.rb:77:in `asset_digest_path'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-rails-2.0.1/lib/sprockets/rails/helper.rb:40:in `compute_asset_path'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/actionpack-4.0.1/lib/action_view/helpers/asset_url_helper.rb:132:in `asset_path'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/ckeditor-4.0.9/app/assets/javascripts/ckeditor/override.js.erb:5:in `block (2 levels) in singleton class'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:341:in `block in each_logical_path'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:324:in `block (2 levels) in each_file'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:314:in `each'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:314:in `each_entry'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:322:in `block in each_file'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:321:in `each'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:321:in `each_file'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:335:in `each_logical_path'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/ckeditor-4.0.9/app/assets/javascripts/ckeditor/override.js.erb:4:in `block in singleton class'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/ckeditor-4.0.9/app/assets/javascripts/ckeditor/override.js.erb:-5:in `instance_eval'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/ckeditor-4.0.9/app/assets/javascripts/ckeditor/override.js.erb:-5:in `singleton class'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/ckeditor-4.0.9/app/assets/javascripts/ckeditor/override.js.erb:-7:in `__tilt_70197619654300'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/context.rb:197:in `block in evaluate'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/context.rb:194:in `each'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/context.rb:194:in `evaluate'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/processed_asset.rb:12:in `initialize'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:374:in `new'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:374:in `block in build_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:395:in `circular_call_protection'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:373:in `build_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/index.rb:94:in `block in build_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/caching.rb:58:in `cache_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/index.rb:93:in `build_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:287:in `find_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/index.rb:61:in `find_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/processed_asset.rb:105:in `each'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/processed_asset.rb:97:in `build_required_assets'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/processed_asset.rb:16:in `initialize'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:374:in `new'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:374:in `block in build_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:395:in `circular_call_protection'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:373:in `build_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/index.rb:94:in `block in build_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/caching.rb:58:in `cache_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/index.rb:93:in `build_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:287:in `find_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/index.rb:61:in `find_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/bundled_asset.rb:37:in `init_with'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/asset.rb:24:in `from_hash'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/caching.rb:54:in `cache_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/index.rb:93:in `build_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/base.rb:287:in `find_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/index.rb:61:in `find_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/manifest.rb:211:in `block in find_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/manifest.rb:257:in `benchmark'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/manifest.rb:210:in `find_asset'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/manifest.rb:119:in `block in compile'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/manifest.rb:118:in `each'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/sprockets/manifest.rb:118:in `compile'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/non-stupid-digest-assets-1.0.3/lib/non-stupid-digest-assets.rb:31:in `compile_with_non_digest'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-rails-2.0.1/lib/sprockets/rails/task.rb:60:in `block (3 levels) in define'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-2.10.1/lib/rake/sprocketstask.rb:146:in `with_logger'
       /tmp/build_c990cd7d-1621-49da-a4b1-3bda79a63b38/vendor/bundle/ruby/2.0.0/gems/sprockets-rails-2.0.1/lib/sprockets/rails/task.rb:59:in `block (2 levels) in define'
```

I have added the rake task described in the readme and still not working.

**Comment by gaaady** [comment]
+1

**Comment by iamryandrake** [comment]
Anyone resolved this issue yet?

**Comment by kimihito** [comment]
+1

**Comment by prussiap** [comment]
@joshualcoffee ever figure out a fix for this?
