### ISSUE TITLE
Paperclip::Errors::MissingRequiredValidatorError, when i try upload file

### ISSUE THREAD

**Issue by Elsopuro** [galetahub/ckeditor#448]
```ruby
Completed 200 OK in 361.1ms (Views: 254.5ms | ActiveRecord: 24.7ms)
Started POST "/ckeditor/pictures?CKEditor=shop_description&CKEditorFuncNum=1&langCode=ru&authenticity_token=78TPsdfsfhGJ73ZvOjV5q72u%2Fk5ONuwICfrn10Iv7BbpVt%2FNE%3D" for xxx at 2014-05-29 14:28:58 +0400
Processing by Ckeditor::PicturesController#create as HTML
  Parameters: {"upload"=>#<ActionDispatch::Http::UploadedFile:0x000000039343a8 @original_filename="schema.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"upload\"; filename=\"schema.jpg\"\r\nContent-Type: image/jpeg\r\n", @tempfile=#<File:/tmp/RackMultipart20140529-32679-10bxpcq>>, "CKEditor"=>"shop_description", "CKEditorFuncNum"=>"1", "langCode"=>"ru", "authenticity_token"=>"78TPhGJ3ZvOjV5q742u/k5ONuwICfrn10Iv7BbpVt/NE="}
Completed 500 Internal Server Error in 42.1ms

Paperclip::Errors::MissingRequiredValidatorError (Paperclip::Errors::MissingRequiredValidatorError):
  paperclip (4.1.1) lib/paperclip/attachment.rb:396:in `ensure_required_validations!'
  paperclip (4.1.1) lib/paperclip/attachment.rb:97:in `assign'
  paperclip (4.1.1) lib/paperclip/has_attached_file.rb:66:in `block in define_setter'
  /varckeditor (4.0.11) app/controllers/ckeditor/application_controller.rb:13:in `respond_with_asset'
  /varckeditor (4.0.11) app/controllers/ckeditor/pictures_controller.rb:12:in `create'
  actionpack (3.2.17) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.17) lib/abstract_controller/base.rb:167:in `process_action'
```

**Comment by kyledecot** [comment]
This is caused by paperclip requiring that you validate the content type ([see here](http://stackoverflow.com/questions/21897725/papercliperrorsmissingrequiredvalidatorerror-with-rails-4)). 

It looks like this has been added to the Picture model so I'm going to assume this isn't an issue anymore. If you're still having problems please reopen this issue.
