### ISSUE TITLE
production error for style.js

### ISSUE THREAD

**Issue by musaffa** [galetahub/ckeditor#522]
I upgraded ckeditor gem from 4.1.0 to 4.1.1 and I got this error in production environment.

```shell
16:19:33 web.1  | started with pid 4420
16:19:34 web.1  | I, [2014-12-29T16:19:34.309738 #4420]  INFO -- : Refreshing Gem list
16:19:38 web.1  | I, [2014-12-29T16:19:38.037191 #4420]  INFO -- : listening on addr=0.0.0.0:3000 fd=9
16:19:38 web.1  | I, [2014-12-29T16:19:38.045214 #4420]  INFO -- : master process ready
16:19:38 web.1  | I, [2014-12-29T16:19:38.045537 #4427]  INFO -- : worker=0 ready
16:19:38 web.1  | I, [2014-12-29T16:19:38.049394 #4430]  INFO -- : worker=1 ready
16:19:38 web.1  | I, [2014-12-29T16:19:38.050978 #4433]  INFO -- : worker=2 ready
16:19:42 web.1  | source=rack-timeout id=d32e4d4e8d6221983813dcf8317c0b40 timeout=10000ms state=ready
16:19:42 web.1  | Started GET "/articles/new" for 127.0.0.1 at 2014-12-29 16:19:42 +0600
16:19:42 web.1  | Processing by ArticlesController#new as HTML
16:19:43 web.1  |   Rendered articles/new.html.haml within layouts/application (116.4ms)
16:19:43 web.1  |   Rendered layouts/_stylesheets.html.haml (1.0ms)
16:19:43 web.1  |   Rendered layouts/_javascripts.html.haml (0.7ms)
16:19:43 web.1  |   Rendered layouts/_js_locale.html.haml (1.0ms)
16:19:43 web.1  |   Rendered layouts/_header.html.haml (17.7ms)
16:19:43 web.1  |   Rendered layouts/_footer.html.haml (1.8ms)
16:19:43 web.1  | Completed 200 OK in 248ms (Views: 155.3ms | ActiveRecord: 4.8ms)
16:19:43 web.1  | Dec 29 16:19:43 musaffa-H55M-S2H rails[4427]: Oink Action: articles#new
16:19:43 web.1  | Dec 29 16:19:43 musaffa-H55M-S2H rails[4427]: Memory usage: 409268 | PID: 4427
16:19:43 web.1  | Dec 29 16:19:43 musaffa-H55M-S2H rails[4427]: Instantiation Breakdown: Total: 2 | User: 1 | Article: 1
16:19:43 web.1  | Dec 29 16:19:43 musaffa-H55M-S2H rails[4427]: Oink Log Entry Complete
16:19:43 web.1  | source=rack-timeout id=d32e4d4e8d6221983813dcf8317c0b40 timeout=10000ms service=366ms state=completed
16:19:43 web.1  | source=rack-timeout id=fbb38abc9b6f614ad306489f0012ab23 timeout=10000ms state=ready
16:19:43 web.1  | source=rack-timeout id=fbb38abc9b6f614ad306489f0012ab23 timeout=10000ms service=1ms state=completed
16:19:43 web.1  | source=rack-timeout id=d5833328d1bca8d649126edc02e781ba timeout=10000ms state=ready
16:19:43 web.1  | source=rack-timeout id=d5833328d1bca8d649126edc02e781ba timeout=10000ms service=2ms state=completed
16:19:43 web.1  | source=rack-timeout id=0216bb68a473127f3a8aa248c350a7c4 timeout=10000ms state=ready
16:19:43 web.1  | source=rack-timeout id=0216bb68a473127f3a8aa248c350a7c4 timeout=10000ms service=3ms state=completed
16:19:43 web.1  | source=rack-timeout id=4e69abc86cee9b9cca6f7ada3d1b7f13 timeout=10000ms state=ready
16:19:43 web.1  | source=rack-timeout id=4e69abc86cee9b9cca6f7ada3d1b7f13 timeout=10000ms service=2ms state=completed
16:19:43 web.1  | source=rack-timeout id=85cb7217a800ea15acf9ee0a696b10bd timeout=10000ms state=ready
16:19:43 web.1  | Started GET "/assets/ckeditor/config.js?t=EAPE" for 127.0.0.1 at 2014-12-29 16:19:43 +0600
16:19:43 web.1  | Dec 29 16:19:43 musaffa-H55M-S2H rails[4433]: Memory usage: 394772 | PID: 4433
16:19:43 web.1  | Dec 29 16:19:43 musaffa-H55M-S2H rails[4433]: Instantiation Breakdown: Total: 0
16:19:43 web.1  | Dec 29 16:19:43 musaffa-H55M-S2H rails[4433]: Oink Log Entry Complete
16:19:43 web.1  | 
16:19:43 web.1  | ActionController::RoutingError (No route matches [GET] "/assets/ckeditor/config.js"):
16:19:43 web.1  |   actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
16:19:43 web.1  |   actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
16:19:43 web.1  |   railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
16:19:43 web.1  |   railties (4.1.8) lib/rails/rack/logger.rb:20:in `block in call'
16:19:43 web.1  |   activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
16:19:43 web.1  |   activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in `tagged'
16:19:43 web.1  |   activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `tagged'
16:19:43 web.1  |   railties (4.1.8) lib/rails/rack/logger.rb:20:in `call'
16:19:43 web.1  |   actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
16:19:43 web.1  |   rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
16:19:43 web.1  |   rack (1.5.2) lib/rack/runtime.rb:17:in `call'
16:19:43 web.1  |   activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
16:19:43 web.1  |   actionpack (4.1.8) lib/action_dispatch/middleware/static.rb:84:in `call'
16:19:43 web.1  |   rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
16:19:43 web.1  |   rack-mini-profiler (0.9.2) lib/mini_profiler/profiler.rb:300:in `call'
16:19:43 web.1  |   rack-timeout (0.1.1) lib/rack/timeout.rb:104:in `call'
16:19:43 web.1  |   railties (4.1.8) lib/rails/engine.rb:514:in `call'
16:19:43 web.1  |   railties (4.1.8) lib/rails/application.rb:144:in `call'
16:19:43 web.1  |   railties (4.1.8) lib/rails/railtie.rb:194:in `public_send'
16:19:43 web.1  |   railties (4.1.8) lib/rails/railtie.rb:194:in `method_missing'
16:19:43 web.1  |   unicorn (4.8.3) lib/unicorn/http_server.rb:576:in `process_client'
16:19:43 web.1  |   unicorn (4.8.3) lib/unicorn/http_server.rb:670:in `worker_loop'
16:19:43 web.1  |   unicorn (4.8.3) lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
16:19:43 web.1  |   unicorn (4.8.3) lib/unicorn/http_server.rb:140:in `start'
16:19:43 web.1  |   unicorn (4.8.3) bin/unicorn:126:in `<top (required)>'
16:19:43 web.1  |   /home/musaffa/.rbenv/versions/2.1.5/bin/unicorn:23:in `load'
16:19:43 web.1  |   /home/musaffa/.rbenv/versions/2.1.5/bin/unicorn:23:in `<main>'
16:19:43 web.1  | 
16:19:43 web.1  | 
16:19:43 web.1  | Processing by ErrorsController#show as */*
16:19:43 web.1  |   Parameters: {"t"=>"EAPE"}
16:19:43 web.1  |   Rendered errors/not_found.html.haml within layouts/error (2.5ms)
16:19:43 web.1  |   Rendered layouts/_stylesheets.html.haml (1.5ms)
16:19:43 web.1  |   Rendered layouts/_javascripts.html.haml (1.7ms)
16:19:43 web.1  | Completed 404 Not Found in 169ms (Views: 88.7ms | ActiveRecord: 5.0ms)
16:19:43 web.1  | source=rack-timeout id=85cb7217a800ea15acf9ee0a696b10bd timeout=10000ms service=244ms state=completed
16:19:44 web.1  | source=rack-timeout id=b41d1574bc737bccd1cf986d3fbccb28 timeout=10000ms state=ready
16:19:44 web.1  | source=rack-timeout id=ef1ca145f49b1ad1d3a6e65d194aa2df timeout=10000ms state=ready
16:19:44 web.1  | source=rack-timeout id=ef1ca145f49b1ad1d3a6e65d194aa2df timeout=10000ms service=2ms state=completed
16:19:44 web.1  | source=rack-timeout id=b41d1574bc737bccd1cf986d3fbccb28 timeout=10000ms service=3ms state=completed
16:19:44 web.1  | source=rack-timeout id=14ba2b2ecf788498e6956aa991c6269d timeout=10000ms state=ready
16:19:44 web.1  | Started GET "/assets/ckeditor/styles.js?t=EAPE" for 127.0.0.1 at 2014-12-29 16:19:44 +0600
16:19:44 web.1  | Dec 29 16:19:44 musaffa-H55M-S2H rails[4427]: Memory usage: 409536 | PID: 4427
16:19:44 web.1  | Dec 29 16:19:44 musaffa-H55M-S2H rails[4427]: Instantiation Breakdown: Total: 0
16:19:44 web.1  | Dec 29 16:19:44 musaffa-H55M-S2H rails[4427]: Oink Log Entry Complete
16:19:44 web.1  | 
16:19:44 web.1  | ActionController::RoutingError (No route matches [GET] "/assets/ckeditor/styles.js"):
16:19:44 web.1  |   actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
16:19:44 web.1  |   actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
16:19:44 web.1  |   railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
16:19:44 web.1  |   railties (4.1.8) lib/rails/rack/logger.rb:20:in `block in call'
16:19:44 web.1  |   activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
16:19:44 web.1  |   activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in `tagged'
16:19:44 web.1  |   activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `tagged'
16:19:44 web.1  |   railties (4.1.8) lib/rails/rack/logger.rb:20:in `call'
16:19:44 web.1  |   actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
16:19:44 web.1  |   rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
16:19:44 web.1  |   rack (1.5.2) lib/rack/runtime.rb:17:in `call'
16:19:44 web.1  |   activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
16:19:44 web.1  |   actionpack (4.1.8) lib/action_dispatch/middleware/static.rb:84:in `call'
16:19:44 web.1  |   rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
16:19:44 web.1  |   rack-mini-profiler (0.9.2) lib/mini_profiler/profiler.rb:300:in `call'
16:19:44 web.1  |   rack-timeout (0.1.1) lib/rack/timeout.rb:104:in `call'
16:19:44 web.1  |   railties (4.1.8) lib/rails/engine.rb:514:in `call'
16:19:44 web.1  |   railties (4.1.8) lib/rails/application.rb:144:in `call'
16:19:44 web.1  |   railties (4.1.8) lib/rails/railtie.rb:194:in `public_send'
16:19:44 web.1  |   railties (4.1.8) lib/rails/railtie.rb:194:in `method_missing'
16:19:44 web.1  |   unicorn (4.8.3) lib/unicorn/http_server.rb:576:in `process_client'
16:19:44 web.1  |   unicorn (4.8.3) lib/unicorn/http_server.rb:670:in `worker_loop'
16:19:44 web.1  |   unicorn (4.8.3) lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
16:19:44 web.1  |   unicorn (4.8.3) lib/unicorn/http_server.rb:140:in `start'
16:19:44 web.1  |   unicorn (4.8.3) bin/unicorn:126:in `<top (required)>'
16:19:44 web.1  |   /home/musaffa/.rbenv/versions/2.1.5/bin/unicorn:23:in `load'
16:19:44 web.1  |   /home/musaffa/.rbenv/versions/2.1.5/bin/unicorn:23:in `<main>'
16:19:44 web.1  | 
16:19:44 web.1  | 
16:19:44 web.1  | Processing by ErrorsController#show as */*
16:19:44 web.1  |   Parameters: {"t"=>"EAPE"}
16:19:44 web.1  |   Rendered errors/not_found.html.haml within layouts/error (2.9ms)
16:19:44 web.1  |   Rendered layouts/_stylesheets.html.haml (1.2ms)
16:19:44 web.1  |   Rendered layouts/_javascripts.html.haml (2.3ms)
16:19:44 web.1  | Completed 404 Not Found in 57ms (Views: 46.4ms | ActiveRecord: 2.7ms)
```

I get this error in the browser:

```shell
Uncaught [CKEDITOR.resourceManager.load] Resource name "default" was not found at "https://app.example/assets/ckeditor/styles.js?t=EAPE
```

My application works fine with gem version 4.1.0.

**Comment by driv3r** [comment]
do you have `ckeditor/config.js` with fingerprint on production after assets:precompile, or without?

**Comment by neilhoff** [comment]
I am getting this same exact error on version 4.1.1 as well.  The production environment is Heroku.  Works fine in Dev.

I can also confirm that 4.1.0 works great in Heroku.

**Comment by JakeTheSnake3p0** [comment]
Rails 4.2, I'm getting the same problem. CKEditor is trying to load non-fingerprinted assets in production. I only have fingerprinted assets in `/public/assets/ckeditor/...`

**Comment by musaffa** [comment]
Ask @galetahub to accept [this pull request](https://github.com/galetahub/ckeditor/pull/538).

**Comment by fmeyer** [comment]
:+1: @galetahub

**Comment by krishnasrihari** [comment]
Thank you, at last I found the solution to fix this issue.
