### ISSUE TITLE
CKeditor + Carrierwave + RMagick Error

### ISSUE THREAD

**Issue by phlegx** [galetahub/ckeditor#527]
Hi!

I use this configuration in the uploader:

``` ruby
class CkeditorPictureUploader < CarrierWave::Uploader::Base
  include Ckeditor::Backend::CarrierWave
  include CarrierWave::RMagick
  include Sprockets::Rails::Helper

  # Choose what kind of storage to use for this uploader:
  storage :file
```

Why I get this error?

``` console
gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require': No such file to load -- mini_magick (LoadError)
        from /gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `block in require'
        from gems/activesupport-4.1.7/lib/active_support/dependencies.rb:230:in `block in load_dependency'
        from gems/activesupport-4.1.7/lib/active_support/dependencies.rb:633:in `new_constants_in'
        from gems/activesupport-4.1.7/lib/active_support/dependencies.rb:230:in `load_dependency'
        from gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require'
        from gems/ckeditor-4.1.1/lib/ckeditor/backend/carrierwave.rb:1:in `<top (required)>'
        from app/uploaders/ckeditor_attachment_file_uploader.rb:4:in `<class:CkeditorAttachmentFileUploader>'
        from app/uploaders/ckeditor_attachment_file_uploader.rb:1:in `<top (required)>'
```

I don't wont to use MiniMagick but **only RMagick** and I don't want to install both libraries. Any idea?

**Comment by pioz** [comment]
+1

**Comment by interestinall** [comment]
+1

**Comment by interestinall** [comment]
Think this might be the problem: https://github.com/galetahub/ckeditor/blob/master/lib/ckeditor/backend/carrierwave.rb#L1

**Comment by MicFin** [comment]
+1
Has a solution come from this issue?

**Comment by paranishian** [comment]
+1

**Comment by Beerbill** [comment]
+1 having this issue, any fix?

**Comment by beydogan** [comment]
+1

**Comment by pioz** [comment]
Issue is solved?
