### ISSUE TITLE
uninitialized constant Ckeditor::Orm (NameError)

### ISSUE THREAD

**Issue by reneweteling** [galetahub/ckeditor#546]
Hey there,

When i boot the server in production modes i get the following error:
````
busyplanet.dev$ bin/rails s -e production
=> Booting WEBrick
=> Rails 4.2.0 application starting in production on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/private/var/www/busyplanet.dev/app/models/ckeditor/asset.rb:2:in `<class:Asset>': uninitialized constant Ckeditor::Orm (NameError)
	from /private/var/www/busyplanet.dev/app/models/ckeditor/asset.rb:1:in `<top (required)>'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:471:in `each'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:471:in `block in eager_load!'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:469:in `each'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:469:in `eager_load!'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:346:in `eager_load!'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application/finisher.rb:56:in `each'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
	from /private/var/www/busyplanet.dev/config/environment.rb:5:in `<top (required)>'
	from /private/var/www/busyplanet.dev/config.ru:3:in `block in <main>'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
	from /private/var/www/busyplanet.dev/config.ru:in `new'
	from /private/var/www/busyplanet.dev/config.ru:in `<main>'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/server.rb:61:in `app'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/server.rb:272:in `start'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/server.rb:80:in `start'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /private/var/www/busyplanet.dev/bin/rails:8:in `require'
	from /private/var/www/busyplanet.dev/bin/rails:8:in `<top (required)>'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/client/rails.rb:27:in `load'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/client/rails.rb:27:in `call'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/client/command.rb:7:in `call'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/client.rb:26:in `run'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.3.3/bin/spring:48:in `<top (required)>'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/binstub.rb:11:in `load'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/rene/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /private/var/www/busyplanet.dev/bin/spring:16:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
````

Than my models/ckeditor/asset.rb is just out of the box
````ruby
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end
````
Oviously everything works fine in developement. Do you have any idea's? Thanks!

Here is my Gemfile:
````
source 'https://rubygems.org'

ruby '2.1.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use SCSS for stylesheets
gem 'sass-rails'
# to import css files.... GAY!!
gem 'sprockets-sass'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
# use slim templates
gem "slim-rails"
# bootstrap
gem 'bootstrap-sass', '~> 3.3.3'
# easily create bootstrap forms
gem 'bootstrap_form'
# select country ( dep of active admin )
gem 'country_select'
# user login dep op Active admin
gem 'clearance', '~> 1.8.1'
# activeadmin
gem 'activeadmin', github: 'activeadmin'

gem 'bootstrap3-datetimepicker-rails', '~> 4.7.14'
gem "select2-rails"
gem 'pg'


# download
gem "typhoeus"
# ckeeditor
gem 'ckeditor'

# for uploading files with cke
gem 'carrierwave'
gem 'mini_magick'
gem 'momentjs-rails'
gem 'holder_rails'
gem 'truncate_html'
# gem 'twitter-bootstrap-calendar'
gem 'bootstrap_calendar_rails'

group :production do
	# Use sqlite3 as the database for Active Record

	# for heroku
	gem 'puma'
	gem 'rails_12factor'
end

group :development do
	
	# xray quick ref to resources	
	gem 'xray-rails'

	# sourcemaps for assets 
  gem 'sass-rails-source-maps', github: 'vhyza/sass-rails-source-maps', branch: 'sass-rails-5.0.0.beta1'
  gem 'coffee-rails-source-maps'

  # pry, inspect your crap
  gem 'pry-rails'

  # schema to scaffold
  gem 'schema_to_scaffold'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  # rails panel
  gem 'meta_request'

  # live reload
  gem 'guard-livereload', require: false

  # dont show assets
  gem 'quiet_assets'

  # # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  # gem 'byebug'

  # # Access an IRB console on exception pages or by using <%= console %> in views
  # gem 'web-console', '~> 2.0'

end

group :test do
	gem 'minitest-reporters'
	gem 'minitest-rails'
	gem 'minitest-rails-capybara'
	gem 'selenium-webdriver'
	gem 'rake'
end
````

**Comment by reneweteling** [comment]
Update, when you disable the eager loading, the server boots, so im guessing a path thats not correct gets called and ckeditor dies...

**Comment by econnally** [comment]
@reneweteling i was getting the same error until i added this to the `config/initializers/ckeditor.rb`:
```
  require "ckeditor/orm/active_record"
```
while updating other stuff i had removed this line to make it look more like the one [in the docs](https://github.com/galetahub/ckeditor#deployment). big mistake.

**Comment by reneweteling** [comment]
@econnally Np, thanks!!
