### ISSUE TITLE
Error  while precompiling assets with CKeditor plugin

### ISSUE THREAD

**Issue by lobenichou** [galetahub/ckeditor#551]
Using Rails 4.1.0 and ruby 2.0.0

Hey so I get the following error when deploying to Heroku or when running `RAILS_ENV=production bundle exec rake assets:precompile.` It was working fine last week. Any help would be appreciated. 

Here is the part where it fails: 

```
I, [2015-04-10T00:45:23.376697 #38459]  INFO -- : Writing /Users/Lo/Documents/web_work/the_litography_project/public/assets/ckeditor/plugins/pagebreak/images/pagebreak-594266a0b9b56f82f9c88f6f37cef250.gif
I, [2015-04-10T00:45:23.609733 #38459]  INFO -- : Writing /Users/Lo/Documents/web_work/the_litography_project/public/assets/ckeditor/plugins/pastefromword/filter/default-6383d14891566d3785bed0f957b3fd69.js
rake aborted!
ExecJS::ProgramError: Unexpected token: operator (<) (line: 1, col: 0, pos: 0)

JS_Parse_Error@/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2359:10632
js_error@/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2359:10860
croak@/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2359:37462
token_error@/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2359:37596
unexpected@/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2359:37690
expr_atom@/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2359:45904
maybe_unary@/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2359:48396
expr_ops@/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2359:49156
maybe_conditional@/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2359:49245
maybe_assign@/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2359:49697
expression@/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2359:50005
simple_statement@/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2359:40941
/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2359:38852
/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2359:38331
/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2359:50345
parse@/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2360:152

eval code
eval@[native code]
/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2614:12
/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:2618:21
/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:1:46
global code@/var/folders/zp/kd_52n_509j3q8tfkfdpsrw40000gn/T/execjs20150410-38459-1vyzupkjs:1:58
  (in /Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/ckeditor-4.1.1/vendor/assets/javascripts/ckeditor/plugins/preview/preview.html)JS_Parse_Error@(execjs):2359:10632
js_error@(execjs):2359:10860
croak@(execjs):2359:37462
token_error@(execjs):2359:37596
unexpected@(execjs):2359:37690
expr_atom@(execjs):2359:45904
maybe_unary@(execjs):2359:48396
expr_ops@(execjs):2359:49156
maybe_conditional@(execjs):2359:49245
maybe_assign@(execjs):2359:49697
expression@(execjs):2359:50005
simple_statement@(execjs):2359:40941
(execjs):2359:38852
(execjs):2359:38331
(execjs):2359:50345
parse@(execjs):2360:152

(execjs):2614:12
(execjs):2618:21
(execjs):1:46
global code@(execjs):1:58
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/execjs-2.5.2/lib/execjs/external_runtime.rb:39:in `exec'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/execjs-2.5.2/lib/execjs/external_runtime.rb:21:in `eval'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/execjs-2.5.2/lib/execjs/external_runtime.rb:46:in `call'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/uglifier-2.7.1/lib/uglifier.rb:212:in `run_uglifyjs'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/uglifier-2.7.1/lib/uglifier.rb:179:in `compile'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/uglifier_compressor.rb:25:in `evaluate'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/context.rb:197:in `block in evaluate'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/context.rb:194:in `each'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/context.rb:194:in `evaluate'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/bundled_asset.rb:25:in `initialize'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/base.rb:377:in `new'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/base.rb:377:in `build_asset'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/index.rb:93:in `build_asset'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/base.rb:287:in `find_asset'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/index.rb:61:in `find_asset'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:211:in `block in find_asset'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:257:in `benchmark'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:210:in `find_asset'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:119:in `block in compile'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:118:in `each'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:118:in `compile'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-2.11.3/lib/rake/sprocketstask.rb:146:in `with_logger'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/gems/bower-rails-0.8.3/lib/tasks/helpers/before_hook.rb:16:in `block (2 levels) in before'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'
/Users/Lo/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `<main>'Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

**Comment by laurenbenichou** [comment]
Ok... So I did some research and I think the error might be related to this: http://stackoverflow.com/a/9730733. The "<" in https://github.com/galetahub/ckeditor/blob/master/vendor/assets/javascripts/ckeditor/plugins/preview/preview.html might be causing the error during precompile. 

````
<script>
// Prevent from DOM clobbering.
if ( typeof window.opener._cke_htmlToLoad == 'string' ) {
	var doc = document;
	doc.open();
	doc.write( window.opener._cke_htmlToLoad );
	doc.close();
	delete window.opener._cke_htmlToLoad;
}
</script>
````


I might be wrong but this seems like the best lead so far.

**Comment by laurenbenichou** [comment]
Still an issue. Don't know how to fix it. Some files in ckedtior's plugin folders are throwing the same error...

**Comment by ajahongir** [comment]
same issue

**Comment by swapnilchincholkar** [comment]
same issue.....

**Comment by mkaszubowski** [comment]
same issue

**Comment by mkaszubowski** [comment]
I've made a fork at https://github.com/mkaszubowski/ckeditor and changed the all this problematic html files with <script> tags to javascript ones and it helped.

**Comment by mkaszubowski** [comment]
I've made a fork ( https://github.com/mkaszubowski/ckeditor ) and replaced all the problematic html files with script tags to javascript ones and it helped

**Comment by vbyno** [comment]
@mkaszubowski, your fork works for me too. Thanks!
Any chance to use this approach in the main repository?

**Comment by laurenbenichou** [comment]
Worked for me @mkaszubowski. Thanks!

**Comment by ardeearam** [comment]
Worked for me @mkaszubowski. Thanks! Submitted a PR to ckeditor-rails https://github.com/tsechingho/ckeditor-rails/pull/72

**Comment by mkaszubowski** [comment]
Cool, I submitted a PR to ckeditor ( https://github.com/galetahub/ckeditor ) before, but unfortunately it got closed.

**Comment by Eepa** [comment]
Thank you @mkaszubowski your solution worked also for our project! 

It is unfortunate that your pull request got closed as this assets precompile error still exists. At least when using [sprockets](https://github.com/rails/sprockets) gem version 2.X and [ckeditor](https://github.com/galetahub/ckeditor) version 4.1.1. I had to make own [fork](https://github.com/Eepa/ckeditor) from [galetahub/ckeditor](https://github.com/galetahub/ckeditor) where I used your solution and downgraded ckeditor gem version to 4.1.1 in order to get things working. In the fork you can find a reference to your solution.
