### ISSUE TITLE
ActiveRecord::RecordInvalid: Validation failed: Data content type "inode/x-empty" is invalid, Data "inode/x-empty" is invalid

### ISSUE THREAD

**Issue by heaven** [galetahub/ckeditor#561]
CKEditor 4.1.1

```
2.1.2 :005 > asset = Ckeditor::Picture.last
  Ckeditor::Picture Load (0.4ms)  SELECT  `ckeditor_assets`.* FROM `ckeditor_assets`  WHERE `ckeditor_assets`.`type` IN ('Ckeditor::Picture')  ORDER BY `ckeditor_assets`.`id` DESC LIMIT 1
 => #<Ckeditor::Picture id: 89642, data_file_name: "sickle.jpg", data_content_type: "image/jpeg", data_file_size: 52393, assetable_id: nil, assetable_type: nil, type: "Ckeditor::Picture", width: 355, height: 644, created_at: "2015-04-29 05:33:27", updated_at: "2015-04-29 05:33:27"> 
2.1.2 :006 > asset.data
 => #<Paperclip::Attachment:0x007fd6ecc59728 @name=:data, @instance=#<Ckeditor::Picture id: 89642, data_file_name: "sickle.jpg", data_content_type: "image/jpeg", data_file_size: 52393, assetable_id: nil, assetable_type: nil, type: "Ckeditor::Picture", width: 355, height: 644, created_at: "2015-04-29 05:33:27", updated_at: "2015-04-29 05:33:27">, @options={:convert_options=>{}, :default_style=>:original, :default_url=>"/assets/nophoto_small.jpg", :escape_url=>true, :restricted_characters=>/[&$+,\/:;=?@<>\[\]\{\}\|\\\^~%# ]/, :filename_cleaner=>nil, :hash_data=>":class/:attachment/:id/:style/:updated_at", :hash_digest=>"SHA1", :interpolator=>Paperclip::Interpolations, :only_process=>[], :path=>":rails_root/public/system/pictures/:id_partition/:style_:basename.:extension", :preserve_files=>false, :processors=>[:thumbnail], :source_file_options=>{}, :storage=>:filesystem, :styles=>{:content=>"800>", :thumb=>"118x100#"}, :url=>"/system/pictures/:id_partition/:style_:basename.:extension", :url_generator=>Paperclip::UrlGenerator, :use_default_time_zone=>true, :use_timestamp=>true, :whiny=>true, :validate_media_type=>true, :check_validity_before_processing=>true}, @post_processing=true, @queued_for_delete=[], @queued_for_write={}, @errors={}, @dirty=false, @interpolator=Paperclip::Interpolations, @url_generator=#<Paperclip::UrlGenerator:0x007fd6ecc59160 @attachment=#<Paperclip::Attachment:0x007fd6ecc59728 ...>, @attachment_options={:convert_options=>{}, :default_style=>:original, :default_url=>"/assets/nophoto_small.jpg", :escape_url=>true, :restricted_characters=>/[&$+,\/:;=?@<>\[\]\{\}\|\\\^~%# ]/, :filename_cleaner=>nil, :hash_data=>":class/:attachment/:id/:style/:updated_at", :hash_digest=>"SHA1", :interpolator=>Paperclip::Interpolations, :only_process=>[], :path=>":rails_root/public/system/pictures/:id_partition/:style_:basename.:extension", :preserve_files=>false, :processors=>[:thumbnail], :source_file_options=>{}, :storage=>:filesystem, :styles=>{:content=>"800>", :thumb=>"118x100#"}, :url=>"/system/pictures/:id_partition/:style_:basename.:extension", :url_generator=>Paperclip::UrlGenerator, :use_default_time_zone=>true, :use_timestamp=>true, :whiny=>true, :validate_media_type=>true, :check_validity_before_processing=>true}>, @source_file_options={}, @whiny=true> 
2.1.2 :007 > asset.data.file?
 => true 
2.1.2 :008 > asset.data.exists?
 => true 
2.1.2 :009 > asset.valid?      
 => false 
2.1.2 :010 > asset.errors.messages
 => {:data_content_type=>["\"inode/x-empty\" is invalid"], :data=>["\"inode/x-empty\" is invalid"]} 
2.1.2 :011 > asset.save!
   (0.2ms)  BEGIN
   (0.1ms)  ROLLBACK
ActiveRecord::RecordInvalid: Validation failed: Data content type "inode/x-empty" is invalid, Data "inode/x-empty" is invalid
    from /Users/heaven/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.7/lib/active_record/validations.rb:57:in `save!'
    from /Users/heaven/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.7/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
    from /Users/heaven/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.7/lib/active_record/transactions.rb:273:in `block in save!'
    from /Users/heaven/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.7/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
    from /Users/heaven/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
    from /Users/heaven/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
    from /Users/heaven/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
    from /Users/heaven/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.7/lib/active_record/transactions.rb:208:in `transaction'
    from /Users/heaven/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.7/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
    from /Users/heaven/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.7/lib/active_record/transactions.rb:273:in `save!'
    from (irb):11
    from /Users/heaven/.rvm/gems/ruby-2.1.2@carmen/gems/railties-4.1.7/lib/rails/commands/console.rb:90:in `start'
    from /Users/heaven/.rvm/gems/ruby-2.1.2@carmen/gems/railties-4.1.7/lib/rails/commands/console.rb:9:in `start'
    from /Users/heaven/.rvm/gems/ruby-2.1.2@carmen/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:69:in `console'
    from /Users/heaven/.rvm/gems/ruby-2.1.2@carmen/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /Users/heaven/.rvm/gems/ruby-2.1.2@carmen/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:10:in `require'
    from bin/rails:10:in `<main>'2.1.2 :012 >
```

**Comment by heaven** [comment]
What is this method for: https://github.com/galetahub/ckeditor/blob/master/lib/ckeditor/backend/paperclip.rb#L47 ? It causes this error.

**Comment by heaven** [comment]
I think you should check for changes first:
```ruby
self.changes
# => "data_file_name"=>[nil, "2015_Profile_Photo.jpg"]
```

If filename changes present (and the new value is not nil) then try `self.file`, otherwise use `self.path` if `self.file?` returns `true`.

**Comment by kyledecot** [comment]
It looks like you know paperclip better than myself so If you want to do a pull request I'd be more than happy to pull it in.

**Comment by richpeck** [comment]
Did this ever get fixed? Same problem.

**Comment by BandanaPandey** [comment]
I was having the same issue, i.e  whenever I did this
```ruby
>   asset = Ckeditor::Picture.first
>   asset.valid?
 => false
>   asset.changes
 => {"data_content_type"=>["image/jpeg", "inode/x-empty"]}
```
It is happening because of this [extract_content_type](https://github.com/galetahub/ckeditor/blob/master/lib/ckeditor/backend/paperclip.rb#L38) as pointed by @heaven .

I solved this by overriding this method in my code ie,
```ruby
def extract_content_type
    if data_content_type.present? && !data_file_name.blank?
      content_types = MIME::Types.type_for(data_file_name)
      self.data_content_type = content_types.first.to_s unless content_types.empty?
    end
end
```

**Comment by richpeck** [comment]
I found the solution for me -- `file` was missing from my system.
