### ISSUE TITLE
Assets compilation fails with recent sprockets

### ISSUE THREAD

**Issue by elik-ru** [galetahub/ckeditor#627]
I have 
    sprockets (3.2.0)
    sprockets-rails (2.3.2)
in my Gemfile.lock

assets compilation fails with the message:

rake aborted!
ArgumentError: wrong number of arguments (2 for 1)
/Library/Ruby/Gems/2.0.0/gems/ckeditor-4.0.11/app/assets/javascripts/ckeditor/override.js.erb:4:in `block in _evaluate_template'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:84:in `call'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:84:in `block (2 levels) in each_logical_path'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:84:in `each'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:84:in `any?'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:84:in `block in each_logical_path'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:223:in `block in stat_tree'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:207:in `block in stat_directory'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:204:in `each'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:204:in `stat_directory'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:222:in `stat_tree'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:105:in `each'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:104:in `each'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:104:in `logical_paths'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:83:in `each'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:83:in `each_logical_path'
/Library/Ruby/Gems/2.0.0/gems/ckeditor-4.0.11/app/assets/javascripts/ckeditor/override.js.erb:4:in `_evaluate_template'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/erb_processor.rb:26:in `call'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/erb_processor.rb:13:in `call'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Library/Ruby/Gems/2.0.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
[ Some more backtrace]

Problem line is here:
app/assets/javascripts/ckeditor/override.js.erb

window.CKEDITOR_ASSETS_MAPPING = {
<% Rails.application.assets.each_logical_path(->(path){ path =~ /ckeditor/ && path != 'ckeditor/override.js' }) do |asset| %>
  "<%= asset %>": "<%= asset_path(asset) %>",
<% end %>
}
and can be fixed by adding second param to filter:

<% Rails.application.assets.each_logical_path(->(path,_){ path =~ /ckeditor/ && path != 'ckeditor/override.js' }) do |asset| %>

Don't know if this will work with other versions of sprockets.

**Comment by elik-ru** [comment]
Damn, i've got very old gem version.
