### ISSUE TITLE
precompile error in Heroku (rails 5.0.0rc1)

### ISSUE THREAD

**Issue by cycorld** [galetahub/ckeditor#663]
I, [2016-06-25T22:29:24.245446 #1214]  INFO -- : Writing /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/public/assets/ckeditor/init-6fd81e3b075505f65f4711a2086be04715ea24cbe41db2e1ce14631f2014d188.js.gz
       rake aborted!
       ExecJS::ProgramError: Unexpected character '#' (line: 15635, col: 0, pos: 1001546)
       Error
       at new JS_Parse_Error (/tmp/execjs20160625-1214-1y9jcyejs:3572:11870)
       at js_error (/tmp/execjs20160625-1214-1y9jcyejs:3572:12089)
       at parse_error (/tmp/execjs20160625-1214-1y9jcyejs:3572:13996)
       at Object.next_token [as input] (/tmp/execjs20160625-1214-1y9jcyejs:3572:19365)
       at next (/tmp/execjs20160625-1214-1y9jcyejs:3572:20712)
       at semicolon (/tmp/execjs20160625-1214-1y9jcyejs:3572:21565)
       at simple_statement (/tmp/execjs20160625-1214-1y9jcyejs:3572:24478)
       at /tmp/execjs20160625-1214-1y9jcyejs:3572:22602
       at /tmp/execjs20160625-1214-1y9jcyejs:3572:21788
       at /tmp/execjs20160625-1214-1y9jcyejs:3573:2092
       at Object.parse (/tmp/execjs20160625-1214-1y9jcyejs:3573:2301)
       at parse (/tmp/execjs20160625-1214-1y9jcyejs:3903:22)
       new JS_Parse_Error ((execjs):3572:11870)
       js_error ((execjs):3572:12089)
       parse_error ((execjs):3572:13996)
       Object.next_token [as input] ((execjs):3572:19365)
       next ((execjs):3572:20712)
       semicolon ((execjs):3572:21565)
       simple_statement ((execjs):3572:24478)
       (execjs):3572:22602
       (execjs):3572:21788
       (execjs):3573:2092
       Object.parse ((execjs):3573:2301)
       parse ((execjs):3903:22)
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:21:in `eval'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:46:in `call'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/uglifier-3.0.0/lib/uglifier.rb:176:in `run_uglifyjs'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/uglifier-3.0.0/lib/uglifier.rb:139:in `compile'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/uglifier_compressor.rb:52:in `call'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/uglifier_compressor.rb:28:in `call'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/loader.rb:60:in `block in load'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/loader.rb:44:in `load'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/cached_environment.rb:47:in `yield'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/cached_environment.rb:47:in `load'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/base.rb:66:in `find_asset'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/base.rb:73:in `find_all_linked_assets'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/manifest.rb:142:in `block in find'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/path_utils.rb:223:in `block in stat_tree'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/path_utils.rb:207:in `block in stat_directory'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/path_utils.rb:204:in `each'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/path_utils.rb:204:in `stat_directory'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/path_utils.rb:222:in `stat_tree'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/legacy.rb:105:in `each'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/legacy.rb:105:in `block in logical_paths'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/legacy.rb:104:in `each'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/legacy.rb:104:in `logical_paths'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/manifest.rb:140:in `find'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/sprockets/manifest.rb:185:in `compile'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-3.6.0/lib/rake/sprocketstask.rb:147:in `with_logger'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
       /tmp/build_53232e4dba7aa102fd461ff0ac4cf879/vendor/bundle/ruby/2.2.0/gems/rake-11.2.0/exe/rake:27:in `<top (required)>'
       Tasks: TOP => assets:precompile

**Comment by cycorld** [comment]
Sorry, It's my fault
