### ISSUE TITLE
Gem update nor bundle update NO UPDATE to Ckeditor 4.2.0

### ISSUE THREAD

**Issue by Sega100500** [galetahub/ckeditor#669]
Gem update nor bundle update NO UPDATE to Ckeditor 4.2.0
It not published in repository ?

**Comment by galetahub** [comment]
Fixed

**Comment by Sega100500** [comment]
@galetahub 
Many Thanks!
Work!

**Comment by Sega100500** [comment]
Error in production
1. rm Gemfile.lock
2. bundle install
3. app run fail

passenger.log:
```
App 24578 stderr: /home/ruby/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:356:in `block in verify_g
App 24578 stderr:   ckeditor = 4.1.6
App 24578 stderr:
App 24578 stderr: The bundle currently has ckeditor locked at 4.2.0.
App 24578 stderr: Try running `bundle update ckeditor`
App 24578 stderr:
App 24578 stderr: If you are updating multiple gems in your Gemfile at once,
App 24578 stderr: try passing them all to `bundle update`
App 24578 stderr:       from /home/ruby/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:331:in `each'
App 24578 stderr:       from /home/ruby/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:331:in `verify
App 24578 stderr:       from /home/ruby/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:200:in `start'
App 24578 stderr:       from /home/ruby/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/resolver.rb:184:in `resolv
App 24578 stderr:       from /home/ruby/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `reso
App 24578 stderr:       from /home/ruby/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `spec
App 24578 stderr:       from /home/ruby/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:185:in `spec
App 24578 stderr:       from /home/ruby/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/definition.rb:174:in `requ
App 24578 stderr:       from /home/ruby/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/environment.rb:19:in `requ
App 24578 stderr:       from /home/ruby/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:14:in `setup'
App 24578 stderr:       from /home/ruby/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
App 24578 stderr:       from /home/ruby/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/setup.rb:19:in `<top (requ
App 24578 stderr:       from /home/ruby/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
App 24578 stderr:       from /home/ruby/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by Sega100500** [comment]
@galetahub 
Several application use 4.1.6 still. But after ```bundle update``` to use 4.2.0 gem it app will fail run in production. In development mode work.

**Comment by Sega100500** [comment]
@galetahub 
This happen in rails 3.2.22
