### ISSUE TITLE
Unknown line indicator   ckeditor/plugins/preview/preview, Line 11, Column 0     }     ^

### ISSUE THREAD

**Issue by erudinsky** [galetahub/ckeditor#734]
Unknown line indicator
  ckeditor/plugins/preview/preview, Line 11, Column 0
    }
    ^

Rails 4.2, paperclip as backend. 

Not sure where this coming from..

**Comment by streeet25** [comment]
rails 5  same issue

**Comment by stephan-roolvink** [comment]
Same here on rails 4.2. 

```
Slim::Parser::SyntaxError: Unknown line indicator
  ckeditor/plugins/preview/preview, Line 11, Column 0
    }
    ^
ckeditor/plugins/preview/preview:11
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/slim-3.0.7/lib/slim/parser.rb:513:in `syntax_error!'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/slim-3.0.7/lib/slim/parser.rb:259:in `unknown_line_indicator'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/slim-3.0.7/lib/slim/parser.rb:250:in `parse_line_indicators'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/slim-3.0.7/lib/slim/parser.rb:192:in `parse_line'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/slim-3.0.7/lib/slim/parser.rb:95:in `call'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/temple-0.7.7/lib/temple/engine.rb:50:in `block in call'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/temple-0.7.7/lib/temple/engine.rb:50:in `each'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/temple-0.7.7/lib/temple/engine.rb:50:in `inject'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/temple-0.7.7/lib/temple/engine.rb:50:in `call'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/temple-0.7.7/lib/temple/mixins/template.rb:10:in `compile'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/temple-0.7.7/lib/temple/templates/tilt.rb:30:in `prepare'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/tilt-2.0.6/lib/tilt/template.rb:90:in `initialize'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/slim-rails-3.1.2/lib/slim-rails/register_engine.rb:6:in `new'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/slim-rails-3.1.2/lib/slim-rails/register_engine.rb:6:in `call'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:134:in `block in find'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `each'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `find'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/srv/healthcare/hermes_d/shared/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/bin/bundle:22:in `load'
/usr/local/rvm/gems/ruby-2.3.3/bin/bundle:22:in `<main>'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by streeet25** [comment]
As i found at [https://github.com/slim-template/slim-rails/issues/140](slim-rails) it some problem with last update, freeze gem version to previous version - gem 'slim-rails', '3.1.1'

**Comment by Hacklor** [comment]
@streeet25 Thank you for this suggestion, it worked for me. This at least circumvents the problem until the real issue can be solved.

**Comment by sepastian** [comment]
Works for me, thanks!

**Comment by hendra** [comment]
Thanks, this solving my problem

**Comment by galetahub** [comment]
It seems some problem with slim-rails gem

**Comment by kensupermen** [comment]
Thanks, 'slim-rails' version  '3.1.1'  solved my problem

**Comment by zhisme** [comment]
So it wasn't resolved yet?

**Comment by zhisme** [comment]
working fine with
`gem 'slim-rails', '3.2.0'`

tested on `rails 5.1.6`
