### ISSUE TITLE
CKeditor image uploader gallery can not open next page `ActionController::UnknownFormat`

### ISSUE THREAD

**Issue by wesley6j** [galetahub/ckeditor#745]
Rails: 5.0.1
CKEditor: 4.2.2 and above

Process:
1. open image uploader
2. click browse server
3. click next in image gallery.

Problem:
server respond with: `Failed to load resource: the server responded with a status of 406 (Not Acceptable)`

log shows the following:
```
I, [2017-05-15T14:53:05.155042 #3088]  INFO -- : [e5d539de-dc9d-45ad-b0b8-3396710ffbd4] Completed 406 Not Acceptable in 18ms (ActiveRecord: 3.0ms)
F, [2017-05-15T14:53:05.156674 #3088] FATAL -- : [e5d539de-dc9d-45ad-b0b8-3396710ffbd4]
F, [2017-05-15T14:53:05.156874 #3088] FATAL -- : [e5d539de-dc9d-45ad-b0b8-3396710ffbd4] ActionController::UnknownFormat (ActionController::UnknownFormat):
F, [2017-05-15T14:53:05.156978 #3088] FATAL -- : [e5d539de-dc9d-45ad-b0b8-3396710ffbd4]
F, [2017-05-15T14:53:05.157120 #3088] FATAL -- : [e5d539de-dc9d-45ad-b0b8-3396710ffbd4] actionpack (5.0.1) lib/action_controller/metal/mime_responds.rb:203:in `respond_to'
[e5d539de-dc9d-45ad-b0b8-3396710ffbd4] /home/rabbit/apps/gaoym/shared/bundle/ruby/2.3.0/bundler/gems/ckeditor-b578def492e7/app/controllers/ckeditor/pictures_controller.rb:8:in `index'
[e5d539de-dc9d-45ad-b0b8-3396710ffbd4] actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
[e5d539de-dc9d-45ad-b0b8-3396710ffbd4] actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'
[e5d539de-dc9d-45ad-b0b8-3396710ffbd4] actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
[e5d539de-dc9d-45ad-b0b8-3396710ffbd4] actionpack (5.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
```

**Comment by wesley6j** [comment]
The cause is that the link is `/ckeditor/pictures.CKEditor` rather than `/ckeditor/pictures?CKEditor`.

I not sure what caused this problem, but replacing this line:

`var url = v.element.prop("href")`

with 

`var url = v.element.prop("href").replace("pictures.CKEditor", "pictures?CKEditor")`
works.

Hope this can help.

**Comment by galetahub** [comment]
Fixed in this commit https://github.com/galetahub/ckeditor/commit/604608bb55b25ae7cf2d791696de6c28bf8c0fa6
