### ISSUE TITLE
Image doesn't upload

### ISSUE THREAD

**Issue by niks123123** [galetahub/ckeditor#752]
Installed ckeditor, editor works fine. I use paperclip for images, did:
`rails generate ckeditor:install --orm=active_record --backend=paperclip`

But every time get error:
`Started POST "/ckeditor/pictures?qqfile=ava.jpg" for *my_ip_here* at 2017-05-23 16:07:09 +0300
Cannot render console from *my_ip_here*! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Ckeditor::PicturesController#create as */*
  Parameters: {"qqfile"=>"ava.jpg"}
Command :: file -b --mime '/tmp/30bb014e5b15dd9fc656d307c2ac78af20170523-18928-mnhugj.jpg'
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/30bb014e5b15dd9fc656d307c2ac78af20170523-18928-42mped.jpg[0]' 2>/dev/null
Command :: identify -format %m '/tmp/30bb014e5b15dd9fc656d307c2ac78af20170523-18928-42mped.jpg[0]'
Command :: convert '/tmp/30bb014e5b15dd9fc656d307c2ac78af20170523-18928-42mped.jpg[0]' -auto-orient -resize "800>" '/tmp/98245426d4551a58244db7235fc430c520170523-18928-bz8j33'
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/30bb014e5b15dd9fc656d307c2ac78af20170523-18928-42mped.jpg[0]' 2>/dev/null
Command :: identify -format %m '/tmp/30bb014e5b15dd9fc656d307c2ac78af20170523-18928-42mped.jpg[0]'
Command :: convert '/tmp/30bb014e5b15dd9fc656d307c2ac78af20170523-18928-42mped.jpg[0]' -auto-orient -resize "118x" -crop "118x100+0+9" +repage '/tmp/98245426d4551a58244db7235fc430c520170523-18928-1ibtsel'
   (0.1ms)  begin transaction
Command :: file -b --mime '/tmp/30bb014e5b15dd9fc656d307c2ac78af20170523-18928-1sz4dl3.jpg'
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/30bb014e5b15dd9fc656d307c2ac78af20170523-18928-42mped.jpg[0]' 2>/dev/null
   (0.1ms)  rollback transaction
Completed 500 Internal Server Error in 87ms (ActiveRecord: 0.7ms)
 
 
 
ArgumentError (wrong number of arguments (given 1, expected 0)):
 
activesupport (5.1.1) lib/active_support/core_ext/string/inflections.rb:181:in `parameterize'
/home/niks/.rvm/gems/ruby-2.3.0/bundler/gems/ckeditor-26a6cc19868f/lib/ckeditor/utils.rb:20:in `parameterize_filename'
/home/niks/.rvm/gems/ruby-2.3.0/bundler/gems/ckeditor-26a6cc19868f/lib/ckeditor/backend/paperclip.rb:33:in `parameterize_filename'
activesupport (5.1.1) lib/active_support/callbacks.rb:413:in `block in make_lambda'
activesupport (5.1.1) lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
activesupport (5.1.1) lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
activesupport (5.1.1) lib/active_support/callbacks.rb:600:in `catch'
activesupport (5.1.1) lib/active_support/callbacks.rb:600:in `block in default_terminator'
activesupport (5.1.1) lib/active_support/callbacks.rb:198:in `block in halting'
activesupport (5.1.1) lib/active_support/callbacks.rb:507:in `block in invoke_before'
activesupport (5.1.1) lib/active_support/callbacks.rb:507:in `each'
activesupport (5.1.1) lib/active_support/callbacks.rb:507:in `invoke_before'
activesupport (5.1.1) lib/active_support/callbacks.rb:130:in `run_callbacks'
activesupport (5.1.1) lib/active_support/callbacks.rb:825:in `_run_create_callbacks'
activerecord (5.1.1) lib/active_record/callbacks.rb:340:in `_create_record'
activerecord (5.1.1) lib/active_record/timestamp.rb:95:in `_create_record'
activerecord (5.1.1) lib/active_record/persistence.rb:563:in `create_or_update'
activerecord (5.1.1) lib/active_record/callbacks.rb:336:in `block in create_or_update'
activesupport (5.1.1) lib/active_support/callbacks.rb:131:in `run_callbacks'
activesupport (5.1.1) lib/active_support/callbacks.rb:825:in `_run_save_callbacks'
activerecord (5.1.1) lib/active_record/callbacks.rb:336:in `create_or_update'
activerecord (5.1.1) lib/active_record/persistence.rb:129:in `save'
activerecord (5.1.1) lib/active_record/validations.rb:44:in `save'
activerecord (5.1.1) lib/active_record/attribute_methods/dirty.rb:35:in `save'
activerecord (5.1.1) lib/active_record/transactions.rb:308:in `block (2 levels) in save'
activerecord (5.1.1) lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
activerecord (5.1.1) lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
activerecord (5.1.1) lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/home/niks/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
activerecord (5.1.1) lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
activerecord (5.1.1) lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
activerecord (5.1.1) lib/active_record/transactions.rb:210:in `transaction'
activerecord (5.1.1) lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
activerecord (5.1.1) lib/active_record/transactions.rb:308:in `block in save'
activerecord (5.1.1) lib/active_record/transactions.rb:323:in `rollback_active_record_state!'
activerecord (5.1.1) lib/active_record/transactions.rb:307:in `save'
activerecord (5.1.1) lib/active_record/suppressor.rb:42:in `save'
/home/niks/.rvm/gems/ruby-2.3.0/bundler/gems/ckeditor-26a6cc19868f/app/controllers/ckeditor/application_controller.rb:13:in `respond_with_asset'
/home/niks/.rvm/gems/ruby-2.3.0/bundler/gems/ckeditor-26a6cc19868f/app/controllers/ckeditor/pictures_controller.rb:15:in `create'
actionpack (5.1.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.1) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.1) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.1) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.1) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.1) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.1) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.1) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.1) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:832:in `call'
railties (5.1.1) lib/rails/engine.rb:522:in `call'
railties (5.1.1) lib/rails/railtie.rb:185:in `public_send'
railties (5.1.1) lib/rails/railtie.rb:185:in `method_missing'
actionpack (5.1.1) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.1.1) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:832:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.1) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.1) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.1) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:20:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.1) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.1) lib/rails/engine.rb:522:in `call'
puma (3.8.2) lib/puma/configuration.rb:224:in `call'
puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
puma (3.8.2) lib/puma/server.rb:435:in `process_client'
puma (3.8.2) lib/puma/server.rb:299:in `block in run'
puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'`

**Comment by ericcf** [comment]
@niks123123 I just experienced the same issue. Here's what I found:

Currently, the `parameterize` method (defined in Rails Active Support string inflections) takes keyword arguments, so trying to call it with `'_'` (as the CKEditor gem does in `utils.rb`) will unfortunately fail. This commit removed a deprecated separator argument: https://github.com/rails/rails/commit/0189f4db6fe518de8909b66b7f30046bac52dedc.

I'll most likely fork this repository and create a pull request to address the issue.

**Comment by ericcf** [comment]
@niks123123 here's the patch that addresses this issue:

```
--- a/lib/ckeditor/utils.rb
+++ b/lib/ckeditor/utils.rb
@@ -16,8 +16,9 @@ module Ckeditor

         extension = File.extname(filename)
         basename = filename.gsub(/#{extension}$/, '')
+        separator_arg = Rails::VERSION::MAJOR < 5 ? '_' : { separator: '_' }

-        [basename.parameterize('_'), extension].join.downcase
+        [basename.parameterize(separator_arg), extension].join.downcase
       end
```

**Comment by jeffblake** [comment]
There's a fix in master branch
