### ISSUE TITLE
Migration Fails with Rails 5

### ISSUE THREAD

**Issue by TargetXOps** [galetahub/ckeditor#775]
After running `rails generate ckeditor:install --orm=active_record --backend=paperclip` on a new Rails 5 project, migrations fail.  

```sh
rails db:migrate

rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateCkeditorAssets < ActiveRecord::Migration[4.2]
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/migration.rb:525:in `inherited'
/Users/scottnelson/Documents/Uversity/cms/db/migrate/20170803175338_create_ckeditor_assets.rb:1:in `<top (required)>'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/migration.rb:962:in `load_migration'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/migration.rb:958:in `migration'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/migration.rb:953:in `disable_ddl_transaction'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/migration.rb:1305:in `use_transaction?'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/migration.rb:1297:in `ddl_transaction'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/migration.rb:1200:in `each'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/migration.rb:1148:in `block in migrate'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/migration.rb:1148:in `migrate'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/migration.rb:1007:in `up'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/migration.rb:985:in `migrate'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/activerecord-5.1.3/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/railties-5.1.3/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/railties-5.1.3/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/railties-5.1.3/lib/rails/command.rb:46:in `invoke'
/Users/scottnelson/.rvm/gems/ruby-2.3.3/gems/railties-5.1.3/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:9:in `require'
bin/rails:9:in `<main>'
```

Solution: specifying the version allows migration to run properly. 
`class CreateCkeditorAssets < ActiveRecord::Migration[4.2]`

**Comment by patricklindsay** [comment]
Fixed in master, release coming soon
