### ISSUE TITLE
Unknown line indicator ckeditor/plugins/wsc/dialogs/ciframe, Line 13, Column 0

### ISSUE THREAD

**Issue by Quintasan** [galetahub/ckeditor#780]
Unfortunately the workaround proposed in #734 did not work for me.

```
Started GET "/admin/login" for 127.0.0.1 at 2017-08-14 11:48:58 +0200
Processing by SessionsController#new as HTML
  Rendering sessions/new.html.haml
  Rendered sessions/new.html.haml (191.3ms)
Completed 500 Internal Server Error in 194ms (ActiveRecord: 0.0ms)



Slim::Parser::SyntaxError - Unknown line indicator
  ckeditor/plugins/wsc/dialogs/ciframe, Line 13, Column 0
    {
    ^
:
  slim (3.0.8) lib/slim/parser.rb:517:in `syntax_error!'
  slim (3.0.8) lib/slim/parser.rb:259:in `unknown_line_indicator'
  slim (3.0.8) lib/slim/parser.rb:250:in `parse_line_indicators'
  slim (3.0.8) lib/slim/parser.rb:192:in `parse_line'
  slim (3.0.8) lib/slim/parser.rb:95:in `call'
  temple (0.8.0) lib/temple/engine.rb:50:in `block in call'
  temple (0.8.0) lib/temple/engine.rb:50:in `call'
  temple (0.8.0) lib/temple/mixins/template.rb:10:in `compile'
  temple (0.8.0) lib/temple/templates/tilt.rb:30:in `prepare'
  tilt (2.0.8) lib/tilt/template.rb:99:in `initialize'
  slim-rails (3.1.2) lib/slim-rails/register_engine.rb:6:in `call'
```

**Comment by patricklindsay** [comment]
Seems this is an issue with Slim
