### ISSUE TITLE
Exception: Terrapin::CommandNotFoundError

### ISSUE THREAD

**Issue by drummerroma** [galetahub/ckeditor#811]
Image attachment is no more working after your replacement of the cocain-gem.

```

2018-06-14 12:58:27.470995 F [1:puma 004 debug_exceptions.rb:7] [["3fabbbf8-42c6-4645-bfb8-d317b5be2834"]] Rails -- Exception: Terrapin::CommandNotFoundError: Terrapin::CommandNotFoundError
2018-06-14 12:58:27.470995 F [1:puma 004 debug_exceptions.rb:7] [["3fabbbf8-42c6-4645-bfb8-d317b5be2834"]] Rails -- Exception: Terrapin::CommandNotFoundError: Terrapin::CommandNotFoundError
/usr/local/bundle/gems/terrapin-0.6.0/lib/terrapin/command_line.rb:82:in `run'
/usr/local/bundle/bundler/gems/ckeditor-dc2cef2c2c33/lib/ckeditor/utils/content_type_detector.rb:31:in `content_type_from_file_command'
/usr/local/bundle/bundler/gems/ckeditor-dc2cef2c2c33/lib/ckeditor/utils/content_type_detector.rb:20:in `detect'
/usr/local/bundle/bundler/gems/ckeditor-dc2cef2c2c33/lib/ckeditor/backend/carrierwave.rb:40:in `extract_content_type'




```

**Comment by robstove** [comment]
We're having the same issue. Is this something well known? Any work arounds?

**Comment by patricklindsay** [comment]
Is this still an issue on `v4.3.0`? if so can I get some reproducible steps along with what version of Rails you're using

**Comment by venkateshkarni** [comment]
This has sloved this issue for me.
brew install imagemagick

**Comment by venkateshkarni** [comment]
This has sloved this issue for me. Ubuntu 18.04.6 LTS
Run sudo apt install imagemagick
